### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by BolisettySujith** [BolisettySujith/J.A.R.V.I.S#4]

**Comment by danger-ahead** [comment]
Hi, can you provide an insight on what could be included further?
I am interested, kindly consider assigning me. Thanks 😄

**Comment by BolisettySujith** [comment]
@danger-ahead  Hi, Thanks for your interest
You can make some changes in the Installation process to make the ppl understand in an easier way, if you got any errors that I have not mentioned you can add in [ERRORS.md](https://github.com/BolisettySujith/J.A.R.V.I.S/blob/main/ERRORS.md) file and if you have any other ideas to make it good you can do...

Thank you😀

**Comment by AyushJain2480** [comment]
https://user-images.githubusercontent.com/96828089/150678861-606d3b0b-f0ff-40d3-a4a1-24a84172e5ba.mp4

**Comment by AyushJain2480** [comment]
https://user-images.githubusercontent.com/96828089/150678959-35c53f77-6920-445d-905a-de3f06c23314.mp4

pls check this  in screen recording part and i already install ffmpeg and placed it also in my directory but it is showing like this in video , any solution ?

**Comment by BolisettySujith** [comment]
@AyushJain2480 can u tell what's the exact issue?

I didn't find any issue in the recording.

**Comment by BolisettySujith** [comment]
@AyushJain2480 this Issue is open for README improvements. 

If u have any bugs or any other issue, open a new issue, and I didn't find any problem in the recording u provided. can u raise an issue and tell me what's the exact problem.

**Comment by AyushJain2480** [comment]
new screen is loading continuously in screen recording part
Because of this I think
In while true
cv2.imshow("screen recorder",frame)

**Comment by BolisettySujith** [comment]
That is actually not a new screen, they are the mirror infinite reflection of the main screen. You can also see this type of effect if u used any screen recording tool like OBS.
Example:
![image](https://user-images.githubusercontent.com/73323807/150680641-d3792282-bfb9-4164-86cd-4e1642109a24.png)

and the same thing happened here
![image](https://user-images.githubusercontent.com/73323807/150680820-0d9348ef-3fea-4fd0-8cc0-2386f2afaf2b.png)

So, after u start the recording u can just minimize that Recoding-screen pop-up.

**Comment by AyushJain2480** [comment]
Ok, thanks for the clarification. 🙂

**Comment by BolisettySujith** [comment]
No problem, thanks for showing interest in the repo, feel free to ⭐ it if u  like😄.

**Comment by AyushJain2480** [comment]
Thanks, I will.

**Comment by Devpuniya** [comment]
Windows PowerShell
Copyright (C) 2013 Microsoft Corporation. All rights reserved.

PS C:\Users\apptec computer> & "C:/Users/apptec computer/AppData/Local/Programs/Python/Python39/python.exe" "c:/Users/apptec computer/Desktop/Jarvis/Jarvis.py"
Traceback (most recent call last):
  File "c:\Users\apptec computer\Desktop\Jarvis\Jarvis.py", line 6, in <module>
    import pywhatkit as kit
  File "C:\Users\apptec computer\AppData\Local\Programs\Python\Python39\lib\site-packages\pywhatkit\__init__.py", line 16, in <module>
    from pywhatkit.whats import (
  File "C:\Users\apptec computer\AppData\Local\Programs\Python\Python39\lib\site-packages\pywhatkit\whats.py", line 7, in <module>
    import pyautogui as pg
  File "C:\Users\apptec computer\AppData\Local\Programs\Python\Python39\lib\site-packages\pyautogui\__init__.py", line 221, in <module>
    locateOnWindow.__doc__ = pyscreeze.locateOnWindow.__doc__
AttributeError: module 'pyscreeze' has no attribute 'locateOnWindow'
This is the error which i am getting can you help me to solve this

**Comment by BolisettySujith** [comment]
ok, maybe try these methods

https://github.com/asweigart/pyautogui/issues/598

https://stackoverflow.com/questions/68354631/am-using-the-pyautogui-module-now-from-automate-the-boring-stuff-with-python-my

**Comment by Devpuniya** [comment]
Windows PowerShell
Copyright (C) 2013 Microsoft Corporation. All rights reserved.

PS C:\Users\apptec computer\Desktop\Jarvis> & "C:/Users/apptec computer/AppData/Local/Programs/Python/Python39/python.exe" "c:/Users/apptec computer/Desktop/Jarvis/Jarvis.py"
Traceback (most recent call last):
  File "c:\Users\apptec computer\Desktop\Jarvis\Jarvis.py", line 6, in <module>
    import pywhatkit
  File "C:\Users\apptec computer\AppData\Local\Programs\Python\Python39\lib\site-packages\pywhatkit\__init__.py", line 16, in <module>
    from pywhatkit.whats import (
  File "C:\Users\apptec computer\AppData\Local\Programs\Python\Python39\lib\site-packages\pywhatkit\whats.py", line 7, in <module>
    import pyautogui as pg
  File "C:\Users\apptec computer\AppData\Local\Programs\Python\Python39\lib\site-packages\pyautogui\__init__.py", line 221, in <module>
    locateOnWindow.__doc__ = pyscreeze.locateOnWindow.__doc__
AttributeError: module 'pyscreeze' has no attribute 'locateOnWindow'
PS C:\Users\apptec computer\Desktop\Jarvis>

**Comment by Devpuniya** [comment]
can you make a video for this

**Comment by Devpuniya** [comment]
and for gui

**Comment by Devpuniya** [comment]
1st error File "c:\Users\apptec computer\Desktop\Jarvis\Jarvis.py", line 6, in
import pywhatkit
File "C:\Users\apptec computer\AppData\Local\Programs\Python\Python39\lib\site-packages\pywhatkit_init_.py", line 16, in
from pywhatkit.whats import (

**Comment by Devpuniya** [comment]
1st error:-
File "c:\Users\apptec computer\Desktop\Jarvis\Jarvis.py", line 6, in
import pywhatkit
File "C:\Users\apptec computer\AppData\Local\Programs\Python\Python39\lib\site-packages\pywhatkit_init_.py", line 16, in
from pywhatkit.whats import (

**Comment by Devpuniya** [comment]
2nd error:-
File "C:\Users\apptec computer\AppData\Local\Programs\Python\Python39\lib\site-packages\pywhatkit\whats.py", line 7, in
import pyautogui as pg
File "C:\Users\apptec computer\AppData\Local\Programs\Python\Python39\lib\site-packages\pyautogui_init_.py", line 221, in
locateOnWindow.doc = pyscreeze.locateOnWindow.doc
AttributeError: module 'pyscreeze' has no attribute 'locateOnWindow'

**Comment by Devpuniya** [comment]
please solve my problem by making video

**Comment by punithan328** [comment]
there is no error in code , in gui the run cmd is working showing listening but not executing any commands...
I'm doing this as college project . Help me ...
